"""
AndroidLayoutAnalyzer - Python Implementation

Analyzes Android layout files and extracts GUI elements with their associated code.
Equivalent to the original AndroidLayoutAnalyzer.jar

Usage:
    python layout_analyzer.py <source_code_path> <method_code_xml> [output_dir]

Input:
    - source_code_path: Root path of Android source code (will auto-find AndroidManifest.xml and res/)
    - method_code_xml: Path to MethodCode.xml generated by method_code_extractor.py

Output:
    {app_name}_ElementCode.xml
"""

import os
import re
import sys
import xml.etree.ElementTree as ET
from typing import Dict, List, Set, Tuple, Optional
from pathlib import Path


class StringAnalyzer:
    """Analyzes strings.xml to get string values."""

    def __init__(self, resource_path: str):
        self.string_map: Dict[str, str] = {}
        self._load_strings(resource_path)

    def _load_strings(self, resource_path: str):
        """Load string values from res/values/strings.xml"""
        # Try res/values/strings.xml first (standard Android structure)
        res_path = os.path.join(resource_path, "res")
        if os.path.exists(res_path):
            strings_path = os.path.join(res_path, "values", "strings.xml")
        else:
            # Fallback to direct path (if resource_path is already res/)
            strings_path = os.path.join(resource_path, "values", "strings.xml")

        if not os.path.exists(strings_path):
            # Try alternative paths
            base_path = res_path if os.path.exists(res_path) else resource_path
            for variant in ["values-en", "values-en-rUS"]:
                alt_path = os.path.join(base_path, variant, "strings.xml")
                if os.path.exists(alt_path):
                    strings_path = alt_path
                    break

        # Load from all XML files in values directory (some projects split strings)
        values_dir = os.path.dirname(strings_path)
        if os.path.exists(values_dir):
            self._load_strings_from_dir(values_dir)
        elif not os.path.exists(strings_path):
            print(f"  Warning: values directory not found at {values_dir}")
            return

    def _load_strings_from_dir(self, values_dir: str):
        """Load strings from all XML files in the values directory."""
        for filename in os.listdir(values_dir):
            if filename.endswith(".xml"):
                filepath = os.path.join(values_dir, filename)
                try:
                    tree = ET.parse(filepath)
                    root = tree.getroot()
                    for string_elem in root.findall(".//string"):
                        name = string_elem.get("name", "")
                        value = string_elem.text or ""
                        if name:
                            self.string_map[name] = value
                except ET.ParseError as e:
                    print(f"  Error parsing {filename}: {e}")

    def get_content(self, string_name: str) -> str:
        """Get string content by name."""
        return self.string_map.get(string_name, "")


class AndroidManifestAnalyzer:
    """Analyzes AndroidManifest.xml to extract Activity list and package name."""

    def __init__(self, resource_path: str):
        self.activity_list: List[str] = []
        self.activity_full_names: List[str] = []
        self.pkg: str = ""
        self._parse_manifest(resource_path)

    def _parse_manifest(self, resource_path: str):
        """Parse AndroidManifest.xml"""
        manifest_path = os.path.join(resource_path, "AndroidManifest.xml")
        if not os.path.exists(manifest_path):
            print(f"  Error: AndroidManifest.xml not found at {manifest_path}")
            return

        try:
            tree = ET.parse(manifest_path)
            root = tree.getroot()

            # Get package name from manifest
            self.pkg = root.get("package", "")

            # If package not in manifest, try build.gradle files (modern Android projects)
            if not self.pkg:
                self.pkg = self._find_package_from_gradle(resource_path)

            # Find all activities
            # Handle Android namespace
            ns = {"android": "http://schemas.android.com/apk/res/android"}

            for activity in root.findall(".//activity", ns):
                # Try different ways to get the name attribute
                name = activity.get("{http://schemas.android.com/apk/res/android}name")
                if name is None:
                    name = activity.get("name", "")

                if name:
                    # Store full name
                    if name.startswith("."):
                        full_name = self.pkg + name
                    elif "." not in name:
                        full_name = self.pkg + "." + name
                    else:
                        full_name = name
                    self.activity_full_names.append(full_name)
                    
                    # Extract simple class name - handle modern naming conventions with suffixes
                    simple_name = name.split(".")[-1]
                    # Remove common suffixes like Activity, ActivityM, Fragment, FragmentM
                    base_name = re.sub(r'(Activity|Fragment)M?$', '', simple_name)
                    
                    # Add both the original simple name and the base name without suffix
                    self.activity_list.append(simple_name)
                    if base_name != simple_name:
                        self.activity_list.append(base_name)

        except ET.ParseError as e:
            print(f"  Error parsing AndroidManifest.xml: {e}")

    def _find_package_from_gradle(self, resource_path: str) -> str:
        """Find package name from build.gradle files (for modern Android projects)."""
        # Look in parent directories for build.gradle or build.gradle.kts
        search_path = resource_path
        for _ in range(5):  # Search up to 5 levels up
            for gradle_name in ["build.gradle.kts", "build.gradle"]:
                gradle_path = os.path.join(search_path, gradle_name)
                if os.path.exists(gradle_path):
                    try:
                        with open(gradle_path, 'r', encoding='utf-8') as f:
                            content = f.read()
                            
                            # Look for variable definitions first (like APP_ID = '...')
                            var_matches = re.findall(r'(?:String|def|val|var)\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*["\']([^"\']+)["\']', content)
                            var_dict = {name: value for name, value in var_matches}
                            
                            # Look for namespace with variable
                            ns_var_match = re.search(r'namespace\s+([A-Za-z_][A-Za-z0-9_]*)', content)
                            if ns_var_match and ns_var_match.group(1) in var_dict:
                                return var_dict[ns_var_match.group(1)]
                            
                            # Look for applicationId with variable
                            app_id_var_match = re.search(r'applicationId\s+([A-Za-z_][A-Za-z0-9_]*)', content)
                            if app_id_var_match and app_id_var_match.group(1) in var_dict:
                                return var_dict[app_id_var_match.group(1)]
                            
                            # Standard patterns
                            match = re.search(r'namespace\s*=?\s*["\']([^"\']+)["\']', content)
                            if match:
                                return match.group(1)
                            match = re.search(r'applicationId\s*=?\s*["\']([^"\']+)["\']', content)
                            if match:
                                return match.group(1)
                            
                            # Look for package name in plugins block (Kotlin DSL)
                            match = re.search(r'id\s*\(\s*["\']com\.android\.[^"\']+["\']\s*\)[\s\S]*?namespace\s*=\s*["\']([^"\']+)["\']', content)
                            if match:
                                return match.group(1)
                    except Exception as e:
                        print(f"  Error parsing gradle file {gradle_path}: {e}")
            search_path = os.path.dirname(search_path)
            if not search_path:
                break
        return ""

    def get_activity_list(self) -> List[str]:
        return self.activity_list

    def get_pkg(self) -> str:
        return self.pkg


class AndroidLayoutAnalyzer:
    """Main analyzer for Android layouts and GUI elements."""

    def __init__(self, resource_path: str, method_code_path: str, source_code_path: str = None):
        self.resource_path = resource_path
        self.source_code_path = source_code_path
        self.string_analyzer = StringAnalyzer(resource_path)

        # Parse manifest
        self.manifest_analyzer = AndroidManifestAnalyzer(resource_path)
        self.activity_list = self.manifest_analyzer.get_activity_list()
        self.pkg = self.manifest_analyzer.get_pkg()

        # Layout/menu/xml file lists
        self.layout_names: List[str] = []
        self.layout_paths: List[str] = []
        self.menu_names: List[str] = []
        self.menu_paths: List[str] = []
        self.xml_names: List[str] = []
        self.xml_paths: List[str] = []

        # Activity to resource mappings
        self.activity_to_layouts: Dict[str, Set[str]] = {}
        self.activity_to_menus: Dict[str, Set[str]] = {}
        self.activity_to_xmls: Dict[str, Set[str]] = {}

        # Method code from MethodCode.xml
        self.methods: Dict[str, str] = {}
        self.java_files: List[ET.Element] = []

        # Source file paths for direct code searching
        self.source_file_paths: List[str] = []

        # Load resources
        self._load_layout_files()
        self._load_method_code(method_code_path)
        self._load_source_files()

    def _load_layout_files(self):
        """Load all layout, menu, xml files."""
        # Determine the base res path
        res_path = os.path.join(self.resource_path, "res")
        if not os.path.exists(res_path):
            # Fallback to resource_path itself (if it's already res/)
            res_path = self.resource_path

        # Load layouts
        layout_dir = os.path.join(res_path, "layout")
        if os.path.exists(layout_dir):
            self._scan_xml_files(layout_dir, self.layout_names, self.layout_paths)

        # Load menus
        menu_dir = os.path.join(res_path, "menu")
        if os.path.exists(menu_dir):
            self._scan_xml_files(menu_dir, self.menu_names, self.menu_paths)

        # Load xml (preferences, etc.)
        xml_dir = os.path.join(res_path, "xml")
        if os.path.exists(xml_dir):
            self._scan_xml_files(xml_dir, self.xml_names, self.xml_paths)

    def _scan_xml_files(self, directory: str, names: List[str], paths: List[str]):
        """Recursively scan for XML files."""
        for root, dirs, files in os.walk(directory):
            for file in files:
                if file.endswith(".xml"):
                    names.append(file.replace(".xml", ""))
                    paths.append(os.path.join(root, file))

    def _load_method_code(self, method_code_path: str):
        """Load method code from MethodCode.xml"""
        if not os.path.exists(method_code_path):
            print(f"  Error: MethodCode.xml not found at {method_code_path}")
            return

        try:
            tree = ET.parse(method_code_path)
            root = tree.getroot()
            self.java_files = list(root)

            # Build method name -> body mapping
            for java_file in self.java_files:
                for method in java_file:
                    method_name = method.get("name", "")
                    method_body = method.text or ""
                    if method_name:
                        self.methods[method_name] = method_body

        except ET.ParseError as e:
            print(f"  Error parsing MethodCode.xml: {e}")

    def _load_source_files(self):
        """Load all Java and Kotlin source file paths for direct code searching."""
        if not self.source_code_path:
            return

        for root, dirs, files in os.walk(self.source_code_path):
            for file in files:
                if file.endswith(".java") or file.endswith(".kt"):
                    self.source_file_paths.append(os.path.join(root, file))

    def _read_source_file(self, path: str) -> str:
        """Read source file content."""
        try:
            with open(path, 'r', encoding='utf-8', errors='ignore') as f:
                return f.read()
        except Exception:
            return ""

    def _get_procedure_content(self, content: str) -> str:
        """Inline expand procedure calls in content (like getProcedureContent in Java)."""
        result = content
        # Find procedure calls like methodName();
        pattern = re.compile(r'([^.\s()]+)\(\);')
        for match in pattern.finditer(content):
            procedure_name = match.group(1)
            if procedure_name in self.methods:
                procedure_content = self.methods[procedure_name]
                if procedure_content:
                    # Append method content after the call
                    result = result.replace(match.group(0), match.group(0) + procedure_content)
        return result

    def _get_alias(self, id_string: str) -> str:
        """Find alias for a preference key (like getAlias in Java)."""
        for path in self.source_file_paths:
            content = self._read_source_file(path)
            # Pattern: variable = "id_string"
            pattern = re.compile(rf'(\S+)\s*=\s*"{re.escape(id_string)}"')
            match = pattern.search(content)
            if match:
                return match.group(1).strip()
        return ""

    def _find_called_methods(self, id_string: str) -> List[Tuple[str, str]]:
        """
        Find methods called on variables initialized with this ID.
        Like getCalledMethods in Java - tracks: variable = findViewById(R.id.xxx); variable.setOnClickListener(...)
        Supports both Java and Kotlin patterns.
        """
        methods_found = []

        # Search in MethodCode.xml
        for java_file in self.java_files:
            methods_list = list(java_file)
            for method in methods_list:
                content = method.text or ""
                self._extract_called_methods(content, id_string, methods_list, methods_found)

        # Also search in source files directly for Kotlin patterns
        for path in self.source_file_paths:
            content = self._read_source_file(path)
            self._extract_called_methods(content, id_string, [], methods_found)
            # Additional Kotlin View Binding patterns in source files
            self._extract_kotlin_binding_methods(content, id_string, methods_found)

        return methods_found

    def _extract_called_methods(self, content: str, id_string: str,
                                 methods_list: list,  # noqa: ARG002 - kept for future use
                                 methods_found: List[Tuple[str, str]]):
        """Extract called methods from content (Java and Kotlin)."""
        if id_string not in content:
            return

        # Find variable initialization: variable = ...idString...
        init_pattern = re.compile(rf'(\S+)\s*=\s*[^;=\n]+{re.escape(id_string)}')
        init_match = init_pattern.search(content)
        if not init_match:
            return

        variable = init_match.group(1).strip()

        # Pattern 1: Java style - variable.methodName(...);
        call_pattern = re.compile(rf'{re.escape(variable)}\.([^.(;\s{{}}]+)\([^{{}}]*\);')
        for call_match in call_pattern.finditer(content):
            method_name = call_match.group(1)
            if method_name in ['setVisibility', 'setText', 'setEnabled', 'setTitle']:
                continue
            method_content = self.methods.get(method_name, "")
            method_content = self._get_procedure_content(method_content)
            if method_content and (method_name, method_content) not in methods_found:
                methods_found.append((method_name, method_content))

        # Pattern 2: Java anonymous class - variable.setOnXxxListener(new OnXxxListener() { ... });
        listener_pattern = re.compile(
            rf'{re.escape(variable)}\.setOn[^()]+\([^{{}}]+\{{[\s\S]*?\}}\);'
        )
        for listener_match in listener_pattern.finditer(content):
            matched = listener_match.group()
            method_name_match = re.search(rf'{re.escape(variable)}\.([^(]+)\(', matched)
            if method_name_match:
                method_name = method_name_match.group(1)
                inner_start = matched.find('{')
                inner_end = matched.rfind('}')
                if inner_start != -1 and inner_end != -1:
                    inner_content = matched[inner_start+1:inner_end].strip()
                    inner_content = self._get_procedure_content(inner_content)
                    if inner_content and (method_name, inner_content) not in methods_found:
                        methods_found.append((method_name, inner_content))

        # Pattern 3: Kotlin lambda - variable.setOnClickListener { ... }
        kotlin_lambda_pattern = re.compile(
            rf'{re.escape(variable)}\.([A-Za-z]+)\s*\{{\s*([\s\S]*?)\s*\}}'
        )
        for lambda_match in kotlin_lambda_pattern.finditer(content):
            method_name = lambda_match.group(1)
            inner_content = lambda_match.group(2).strip()
            inner_content = self._get_procedure_content(inner_content)
            if inner_content and (method_name, inner_content) not in methods_found:
                methods_found.append((method_name, inner_content))

        # Pattern 4: Method calls with variable as parameter
        param_pattern = re.compile(rf'([A-Za-z0-9]+)\([^)]*{re.escape(variable)}[^)]*\)')
        for param_match in param_pattern.finditer(content):
            method_name = param_match.group(1)
            method_content = self.methods.get(method_name, "")
            if method_content:
                method_content = self._get_procedure_content(method_content)
                if method_content and (method_name, method_content) not in methods_found:
                    methods_found.append((method_name, method_content))

    def _extract_kotlin_binding_methods(self, content: str, id_string: str,
                                         methods_found: List[Tuple[str, str]]):
        """Extract methods from Kotlin View Binding patterns."""
        # Extract the view name from R.id.xxx
        id_name = id_string.replace("R.id.", "")

        # Convert snake_case to camelCase for View Binding
        # e.g., my_button -> myButton
        camel_case_name = ''.join(
            word.capitalize() if i > 0 else word.lower()
            for i, word in enumerate(id_name.split('_'))
        )
        
        # Define various binding variable names used in Kotlin/Java
        binding_vars = ["binding", "viewBinding", "mBinding", "b", "databinding"]
        
        # Process each binding variable name
        for binding_var in binding_vars:
            # Pattern 1: binding.viewName.setOnClickListener { ... }
            binding_lambda_pattern = re.compile(
                rf'{binding_var}\.{camel_case_name}\.([A-Za-z]+)\s*\{{\s*([\s\S]*?)\s*\}}'
            )
            for match in binding_lambda_pattern.finditer(content):
                method_name = match.group(1)
                inner_content = match.group(2).strip()
                inner_content = self._get_procedure_content(inner_content)
                if inner_content and (method_name, inner_content) not in methods_found:
                    methods_found.append((method_name, inner_content))

            # Pattern 2: binding.viewName.setOnClickListener(this) or similar
            binding_call_pattern = re.compile(
                rf'{binding_var}\.{camel_case_name}\.([A-Za-z]+)\([^)]*\)'
            )
            for match in binding_call_pattern.finditer(content):
                method_name = match.group(1)
                if method_name in ['setVisibility', 'setText', 'setEnabled', 'setTitle']:
                    continue
                method_content = self.methods.get(method_name, "")
                if method_content:
                    method_content = self._get_procedure_content(method_content)
                    if method_content and (method_name, method_content) not in methods_found:
                        methods_found.append((method_name, method_content))

            # Pattern 3: Also try original snake_case name
            binding_lambda_pattern2 = re.compile(
                rf'{binding_var}\.{id_name}\.([A-Za-z]+)\s*\{{\s*([\s\S]*?)\s*\}}'
            )
            for match in binding_lambda_pattern2.finditer(content):
                method_name = match.group(1)
                inner_content = match.group(2).strip()
                inner_content = self._get_procedure_content(inner_content)
                if inner_content and (method_name, inner_content) not in methods_found:
                    methods_found.append((method_name, inner_content))
        
        # Pattern 4: Direct findViewById with lambda - findViewById<Button>(R.id.xxx).setOnClickListener { ... }
        find_view_pattern = re.compile(
            rf'findViewById\s*<[^>]*>\s*\(\s*{re.escape(id_string)}\s*\)\.([A-Za-z]+)\s*\{{\s*([\s\S]*?)\s*\}}'
        )
        for match in find_view_pattern.finditer(content):
            method_name = match.group(1)
            inner_content = match.group(2).strip()
            inner_content = self._get_procedure_content(inner_content)
            if inner_content and (method_name, inner_content) not in methods_found:
                methods_found.append((method_name, inner_content))
                
        # Pattern 5: Modern Kotlin synthetic properties - button.setOnClickListener { ... }
        # This works when the ID is directly used as a variable name in Kotlin
        synthetic_pattern = re.compile(
            rf'(?<![.\w]){camel_case_name}\.([A-Za-z]+)\s*\{{\s*([\s\S]*?)\s*\}}'
        )
        for match in synthetic_pattern.finditer(content):
            method_name = match.group(1)
            inner_content = match.group(2).strip()
            inner_content = self._get_procedure_content(inner_content)
            if inner_content and (method_name, inner_content) not in methods_found:
                methods_found.append((method_name, inner_content))

    def _add_property(self, ui_elem: ET.Element, method_name: str, method_content: str):
        """Add text/title properties from setText/setTitle calls."""
        if method_name not in ['setText', 'setTitle']:
            return

        # Find R.string.xxx references in method calls
        pattern = re.compile(rf'{method_name}\([^)]*R\.string\.([^();{{}}]+)')
        properties = set()
        for match in pattern.finditer(method_content):
            properties.add(match.group(1))

        if not properties:
            return

        property_name = 'text' if method_name == 'setText' else 'title'
        property_content_name = 'textContent' if method_name == 'setText' else 'titleContent'

        prop_text = ''.join(f'[{p}]' for p in properties)
        prop_content = ''.join(f'[{self.string_analyzer.get_content(p)}]' for p in properties)

        if ui_elem.tag == 'UIElement':
            ui_elem.set(property_name, prop_text)
            ui_elem.set(property_content_name, prop_content)
        elif ui_elem.tag == 'Preference':
            ui_elem.set('title', prop_text)
            ui_elem.set('titleContent', prop_content)

    def build_layout_list_by_activity(self):
        """Build mapping of activities to their layouts/menus/xmls."""
        java_file_to_layouts: Dict[str, Set[str]] = {}
        java_file_to_menus: Dict[str, Set[str]] = {}
        java_file_to_xmls: Dict[str, Set[str]] = {}
        
        # Map common layout names to activities based on naming convention
        # This is a fallback for modern Android projects
        activity_to_default_layouts: Dict[str, Set[str]] = {}
        
        # First pass - collect all layouts and map by naming convention
        for layout_name in self.layout_names:
            # Map activity_xxx.xml layouts to corresponding activities
            if layout_name.startswith("activity_"):
                activity_name = layout_name[len("activity_"):]
                # Try different activity name variants
                for variant in [
                    activity_name,                    # activity_main.xml -> Main
                    activity_name.capitalize(),       # activity_main.xml -> Main
                    f"{activity_name}Activity",       # activity_main.xml -> MainActivity
                    f"{activity_name}ActivityM",      # activity_main.xml -> MainActivityM
                ]:
                    if variant not in activity_to_default_layouts:
                        activity_to_default_layouts[variant] = set()
                    activity_to_default_layouts[variant].add(layout_name)
        
        print(f"  Default layout mapping based on naming convention:")
        for activity, layouts in activity_to_default_layouts.items():
            print(f"    {activity}: {layouts}")

        for java_file in self.java_files:
            java_file_name = java_file.get("name", "").replace(".java", "").replace(".kt", "")

            layout_set: Set[str] = set()
            menu_set: Set[str] = set()
            xml_set: Set[str] = set()

            # Search in all methods of this file
            for method in java_file:
                method_content = method.text or ""

                # Find layout references - standard R.layout.xxx pattern
                for layout_name in self.layout_names:
                    if f"R.layout.{layout_name}" in method_content:
                        layout_set.add(layout_name)
                        
                # Find layout references - modern binding pattern
                # binding = ActivityMainBinding.inflate(layoutInflater)
                for layout_name in self.layout_names:
                    # Convert layout_name to binding class name
                    # activity_main -> ActivityMainBinding
                    binding_class = ''.join(
                        word.capitalize() for word in layout_name.split('_')
                    ) + "Binding"
                    
                    if binding_class in method_content:
                        layout_set.add(layout_name)

                # Find menu references
                for menu_name in self.menu_names:
                    if f"R.menu.{menu_name}" in method_content:
                        menu_set.add(menu_name)

                # Find xml references
                for xml_name in self.xml_names:
                    if f"R.xml.{xml_name}" in method_content:
                        xml_set.add(xml_name)
                        
                # Look for setContentView calls with layout IDs
                content_view_pattern = re.compile(r'setContentView\s*\(\s*R\.layout\.([a-zA-Z0-9_]+)\s*\)')
                for match in content_view_pattern.finditer(method_content):
                    layout_name = match.group(1)
                    if layout_name in self.layout_names:
                        layout_set.add(layout_name)

            # Add included layouts
            layout_set.update(self._get_included_layouts(layout_set, menu_set, xml_set))
            menu_set.update(self._get_included_menus(layout_set, menu_set, xml_set))
            
            # Add default layouts based on naming convention
            if java_file_name in activity_to_default_layouts:
                layout_set.update(activity_to_default_layouts[java_file_name])
            
            # For activities without layouts, try to find a matching layout by name
            if java_file_name in self.activity_list and not layout_set:
                # Try to find layouts that might match this activity
                base_name = re.sub(r'(Activity|Fragment)M?$', '', java_file_name).lower()
                for layout_name in self.layout_names:
                    if base_name in layout_name:
                        layout_set.add(layout_name)
                        print(f"  Added layout {layout_name} to {java_file_name} based on name matching")

            if layout_set or java_file_name in self.activity_list:
                java_file_to_layouts[java_file_name] = layout_set
            if menu_set or java_file_name in self.activity_list:
                java_file_to_menus[java_file_name] = menu_set
            if xml_set or java_file_name in self.activity_list:
                java_file_to_xmls[java_file_name] = xml_set

        # Handle fragments - merge their layouts into activities that use them
        all_files = set(java_file_to_layouts.keys())
        fragments = all_files - set(self.activity_list)

        for java_file in self.java_files:
            java_file_name = java_file.get("name", "").replace(".java", "").replace(".kt", "")
            if java_file_name not in all_files:
                continue

            for method in java_file:
                method_content = method.text or ""
                for fragment in fragments:
                    if fragment in method_content:
                        # Merge fragment's resources into this file
                        if java_file_name in java_file_to_layouts and fragment in java_file_to_layouts:
                            java_file_to_layouts[java_file_name].update(
                                java_file_to_layouts.get(fragment, set())
                            )
                        if java_file_name in java_file_to_menus and fragment in java_file_to_menus:
                            java_file_to_menus[java_file_name].update(
                                java_file_to_menus.get(fragment, set())
                            )
                        if java_file_name in java_file_to_xmls and fragment in java_file_to_xmls:
                            java_file_to_xmls[java_file_name].update(
                                java_file_to_xmls.get(fragment, set())
                            )
        
        # Assign default layouts for activities that don't have any
        # This is a last resort for modern Android projects
        common_layouts = []
        for layout_name in self.layout_names:
            if layout_name.startswith("activity_") or "main" in layout_name:
                common_layouts.append(layout_name)
        
        # Sort by importance - main layouts first
        common_layouts.sort(key=lambda x: 0 if "main" in x else 1)
        
        # Ensure each activity has at least one layout
        for activity in self.activity_list:
            if activity not in java_file_to_layouts or not java_file_to_layouts[activity]:
                java_file_to_layouts[activity] = set()
                
                # Try to find a matching layout by activity name
                base_name = re.sub(r'(Activity|Fragment)M?$', '', activity).lower()
                matched = False
                
                for layout_name in self.layout_names:
                    if base_name in layout_name:
                        java_file_to_layouts[activity].add(layout_name)
                        print(f"  Assigned layout {layout_name} to {activity} based on name matching")
                        matched = True
                        break
                
                # If no match found, assign a common layout
                if not matched and common_layouts:
                    java_file_to_layouts[activity].add(common_layouts[0])
                    print(f"  Assigned default layout {common_layouts[0]} to {activity}")

        self.activity_to_layouts = java_file_to_layouts
        self.activity_to_menus = java_file_to_menus
        self.activity_to_xmls = java_file_to_xmls

    def _get_included_layouts(self, layouts: Set[str], menus: Set[str], xmls: Set[str]) -> Set[str]:
        """Get layouts included via <include> tags."""
        included = set()

        for layout_name in layouts:
            if layout_name in self.layout_names:
                idx = self.layout_names.index(layout_name)
                included.update(self._find_includes(self.layout_paths[idx], "layout"))

        return included

    def _get_included_menus(self, layouts: Set[str], menus: Set[str], xmls: Set[str]) -> Set[str]:
        """Get menus referenced in layouts."""
        included = set()

        for layout_name in layouts:
            if layout_name in self.layout_names:
                idx = self.layout_names.index(layout_name)
                included.update(self._find_menu_references(self.layout_paths[idx]))

        return included

    def _find_includes(self, xml_path: str, resource_type: str) -> Set[str]:
        """Find included layouts in an XML file."""
        included = set()
        try:
            tree = ET.parse(xml_path)
            root = tree.getroot()

            for include in root.iter("include"):
                layout_ref = include.get("layout", "")
                if f"@{resource_type}/" in layout_ref:
                    layout_name = layout_ref.split("/")[-1]
                    included.add(layout_name)

        except ET.ParseError:
            pass

        return included

    def _find_menu_references(self, xml_path: str) -> Set[str]:
        """Find menu references in layout XML."""
        menus = set()
        try:
            tree = ET.parse(xml_path)
            root = tree.getroot()

            # Check all elements for menu attribute
            for elem in root.iter():
                menu_ref = elem.get("menu", "") or elem.get(
                    "{http://schemas.android.com/apk/res/android}menu", ""
                )
                if "@menu/" in menu_ref:
                    menu_name = menu_ref.split("/")[-1]
                    menus.add(menu_name)

        except ET.ParseError:
            pass

        return menus

    def _get_id(self, element: ET.Element) -> str:
        """Extract resource ID from element."""
        # Try multiple ways to get the ID
        id_val = element.get("id", "") or element.get(
            "{http://schemas.android.com/apk/res/android}id", ""
        )
        
        # Also try android:id attribute without namespace
        if not id_val:
            id_val = element.get("android:id", "")
            
        # Try other common attributes that might contain IDs
        if not id_val:
            for attr in ["name", "android:name", "android:tag"]:
                id_val = element.get(attr, "")
                if id_val:
                    break
        
        if not id_val:
            return ""

        # Convert @+id/xxx or @id/xxx to package:id/xxx format
        match = re.search(r"id/(.+)", id_val)
        if match:
            id_part = match.group(1)
            # Clean up any trailing attributes or quotes
            id_part = id_part.split('"')[0].split("'")[0].strip()
            return f"{self.pkg}:id/{id_part}"
            
        # If it's not in id/xxx format but looks like a direct ID
        if id_val and not id_val.startswith("@") and not ":" in id_val:
            return f"{self.pkg}:id/{id_val}"
            
        return ""

    def _get_text(self, element: ET.Element) -> str:
        """Extract text attribute from element."""
        text = element.get("text", "") or element.get(
            "{http://schemas.android.com/apk/res/android}text", ""
        )

        # If it's a string reference, extract the name
        match = re.search(r"@string/(.+)", text)
        if match:
            return match.group(1)
        return ""

    def _get_title(self, element: ET.Element) -> str:
        """Extract title attribute from element."""
        title = element.get("title", "") or element.get(
            "{http://schemas.android.com/apk/res/android}title", ""
        )

        match = re.search(r"@string/(.+)", title)
        if match:
            return match.group(1)
        return ""

    def _get_key(self, element: ET.Element) -> str:
        """Extract key attribute from Preference element."""
        key = element.get("key", "") or element.get(
            "{http://schemas.android.com/apk/res/android}key", ""
        )

        if "@string/" in key:
            match = re.search(r"@string/(.+)", key)
            if match:
                return f"string/{match.group(1)}"
        return key

    def _get_id_string(self, id_val: str, elem_type: str) -> str:
        """Convert ID to R.id.xxx format for code searching."""
        if elem_type == "Preference":
            if "string/" in id_val:
                return "R.string." + id_val.split("string/")[-1]
            return id_val
        else:
            parts = id_val.split("/")
            return "R.id." + parts[-1] if parts else ""

    def _find_case_segments(self, id_string: str) -> List[Tuple[str, str]]:
        """Find case statements that handle this ID (Java switch/case and Kotlin when)."""
        segments = []

        # Search in MethodCode.xml
        for java_file in self.java_files:
            for method in java_file:
                content = method.text or ""
                self._extract_case_segments(content, id_string, segments)

        # Also search in source files directly (like original Java implementation)
        for path in self.source_file_paths:
            content = self._read_source_file(path)
            self._extract_case_segments(content, id_string, segments)

        return segments

    def _extract_case_segments(self, content: str, id_string: str, segments: List[Tuple[str, str]]):
        """Extract case/when segments from content."""
        # Pattern 1: Java switch/case - case R.id.xxx: ... (break|case|default)
        java_pattern = rf"case\s+{re.escape(id_string)}\s*:([\s\S]+?)(?:break|case\s|default)"
        for match in re.finditer(java_pattern, content):
            segment = match.group(1).strip()
            segment = self._get_procedure_content(segment)
            if segment and ("caseSegment", segment) not in segments:
                segments.append(("caseSegment", segment))

        # Pattern 2: Kotlin when - R.id.xxx -> { ... } or R.id.xxx -> expression
        # Match: R.id.xxx -> { ... }
        kotlin_block_pattern = rf"{re.escape(id_string)}\s*->\s*\{{([\s\S]+?)\}}"
        for match in re.finditer(kotlin_block_pattern, content):
            segment = match.group(1).strip()
            segment = self._get_procedure_content(segment)
            if segment and ("whenSegment", segment) not in segments:
                segments.append(("whenSegment", segment))

        # Match: R.id.xxx -> expression (single line, no braces)
        kotlin_expr_pattern = rf"{re.escape(id_string)}\s*->\s*([^\n\}}]+)"
        for match in re.finditer(kotlin_expr_pattern, content):
            segment = match.group(1).strip()
            # Skip if it's just a brace (already handled above)
            if segment.startswith('{'):
                continue
            segment = self._get_procedure_content(segment)
            if segment and ("whenSegment", segment) not in segments:
                segments.append(("whenSegment", segment))

    def _find_if_segments(self, id_string: str) -> List[Tuple[str, str]]:
        """Find if statements that check this ID."""
        segments = []

        # Search in MethodCode.xml
        for java_file in self.java_files:
            for method in java_file:
                content = method.text or ""

                # Match: if (...id_string...) { ... }
                pattern = rf"if\s*\([^)]*{re.escape(id_string)}[^)]*\)\s*\{{([^}}]+)\}}"
                for match in re.finditer(pattern, content):
                    segment = match.group(1).strip()
                    segment = self._get_procedure_content(segment)
                    if segment:
                        segments.append(("ifSegment", segment))

        # Also search in source files directly
        for path in self.source_file_paths:
            content = self._read_source_file(path)
            pattern = rf"if\s*\([^)]*{re.escape(id_string)}[^)]*\)\s*\{{([^}}]+)\}}"
            for match in re.finditer(pattern, content):
                segment = match.group(1).strip()
                segment = self._get_procedure_content(segment)
                if segment and ("ifSegment", segment) not in segments:
                    segments.append(("ifSegment", segment))

        return segments

    def _find_onclick_method(self, element: ET.Element) -> Optional[Tuple[str, str]]:
        """Find onClick method bound in XML."""
        onclick = element.get("onClick", "") or element.get(
            "{http://schemas.android.com/apk/res/android}onClick", ""
        )

        if onclick and onclick in self.methods:
            return (onclick, self.methods[onclick])
        return None

    def _find_relevant_methods(self, id_string: str) -> List[Tuple[str, str]]:
        """Find methods that reference this ID."""
        methods_found = []

        for java_file in self.java_files:
            for method in java_file:
                method_name = method.get("name", "")
                content = method.text or ""

                if id_string in content and not method_name.startswith("on"):
                    # Extract relevant lines
                    relevant_lines = []
                    for line in content.split("\n"):
                        if id_string in line:
                            relevant_lines.append(line.strip())

                    if relevant_lines:
                        methods_found.append((method_name, "\n".join(relevant_lines)))

        return methods_found

    def _add_ui_element(self, activity_elem: ET.Element, layout_elem: ET.Element):
        """Add UI element to activity with its associated code."""
        tag = layout_elem.tag.lower()

        # Extract the base tag name from fully qualified class names
        # e.g., com.mirfatif.permissionmanagerx.fwk.MyLinearLayout -> linearlayout
        base_tag = tag.split(".")[-1].lower()
        if "}" in base_tag:  # Handle namespaced tags like {http://...}tag
            base_tag = base_tag.split("}")[-1]

        print(f"      Processing element: {tag} (base: {base_tag})")

        # Handle NavigationView - extract menu items from referenced menu
        if "navigationview" in base_tag or "navigation" in base_tag:
            menu_ref = layout_elem.get("{http://schemas.android.com/apk/res-auto}menu") or \
                       layout_elem.get("menu") or \
                       layout_elem.get("{http://schemas.android.com/apk/res/android}menu")
            if menu_ref:
                # Extract menu name from @menu/xxx
                if "/" in menu_ref:
                    menu_name = menu_ref.split("/")[-1]
                    print(f"        Found NavigationView with menu: {menu_name}")
                    self._add_menu_items(activity_elem, menu_name)

        # Skip layout containers - check both the original tag and the base tag
        if "layout" in tag or "layout" in base_tag:
            print(f"        Skipping layout container, processing {len(layout_elem)} children")
            for child in layout_elem:
                self._add_ui_element(activity_elem, child)
            return
        
        # Check if this element has an ID
        elem_id = self._get_id(layout_elem)
        print(f"        Element ID: {elem_id}")
        
        # Get text and title for identification even if no ID
        text = self._get_text(layout_elem)
        if not text:
            text = self._get_title(layout_elem)
        print(f"        Text/Title: {text}")
        
        # Generate a synthetic ID if needed based on tag and text
        synthetic_id = ""
        if not elem_id and (text or "button" in base_tag or "text" in base_tag):
            # Create a synthetic ID for important elements without IDs
            if text:
                synthetic_id = f"{self.pkg}:id/synthetic_{base_tag}_{text.lower().replace(' ', '_')}"
            else:
                synthetic_id = f"{self.pkg}:id/synthetic_{base_tag}_{len(list(activity_elem))}"
            print(f"        Generated synthetic ID: {synthetic_id}")
        
        # Use synthetic ID if no real ID
        if not elem_id:
            elem_id = synthetic_id
        
        # Handle Preference elements - check both tag and base tag
        if "preference" in tag or "preference" in base_tag:
            print(f"        Adding preference element")
            pref_elem = ET.SubElement(activity_elem, "Preference")
            key = self._get_key(layout_elem)
            title = self._get_title(layout_elem)

            pref_elem.set("key", key)
            pref_elem.set("title", title)
            pref_elem.set("titleContent", self.string_analyzer.get_content(title))

            # Add associated code
            self._add_code(pref_elem, key, layout_elem, "Preference")
        else:
            # Regular UI element - only add if it has ID or text (skip empty elements)
            if elem_id or text:
                print(f"        Adding UI element with ID: {elem_id}, text: {text}")
                ui_elem = ET.SubElement(activity_elem, "UIElement")
                
                ui_elem.set("id", elem_id or "")  # Ensure we don't set None
                ui_elem.set("text", text or "")   # Ensure we don't set None
                ui_elem.set("textContent", self.string_analyzer.get_content(text or ""))
                
                # Store original tag for reference
                ui_elem.set("tag", tag)
                ui_elem.set("baseTag", base_tag)

                # Add associated code
                self._add_code(ui_elem, elem_id, layout_elem, "UIElement")
            else:
                print(f"        Skipping element - no ID or text")

        # Process children - many custom views contain standard Android views
        if len(layout_elem) > 0:
            print(f"        Processing {len(layout_elem)} children")
            for child in layout_elem:
                self._add_ui_element(activity_elem, child)

    def _add_menu_items(self, activity_elem: ET.Element, menu_name: str):
        """
        Add menu items from a menu XML file to the activity.
        This handles NavigationView menus and similar menu references.
        """
        if menu_name not in self.menu_names:
            print(f"        Warning: Menu '{menu_name}' not found in menu_names")
            return

        idx = self.menu_names.index(menu_name)
        menu_path = self.menu_paths[idx]

        try:
            tree = ET.parse(menu_path)
            menu_root = tree.getroot()
            self._process_menu_element(activity_elem, menu_root)
            print(f"        Processed menu: {menu_name}")
        except ET.ParseError as e:
            print(f"        Error parsing menu {menu_name}: {e}")

    def _process_menu_element(self, activity_elem: ET.Element, menu_elem: ET.Element):
        """Recursively process menu elements and add items."""
        for child in menu_elem:
            # Get the tag name without namespace
            tag = child.tag
            if "}" in tag:
                tag = tag.split("}")[-1]

            if tag == "item":
                # Extract item attributes
                item_id = self._get_id(child)
                title = self._get_title(child)
                title_content = self.string_analyzer.get_content(title) if title else ""

                if item_id or title:
                    print(f"          Adding menu item: id={item_id}, title={title}")
                    ui_elem = ET.SubElement(activity_elem, "UIElement")
                    ui_elem.set("id", item_id or "")
                    ui_elem.set("text", title or "")
                    ui_elem.set("textContent", title_content)
                    ui_elem.set("tag", "MenuItem")
                    ui_elem.set("baseTag", "menuitem")

                    # Add associated code - by id if available
                    if item_id:
                        self._add_code(ui_elem, item_id, child, "UIElement")

                    # Also try to find code by title string resource (for menu items without id)
                    # This helps match menu items that are handled by title text
                    if title:
                        self._add_code_by_title(ui_elem, title)

            elif tag == "group" or tag == "menu":
                # Recursively process groups and submenus
                self._process_menu_element(activity_elem, child)

    def _add_code(self, ui_elem: ET.Element, id_val: str, layout_elem: ET.Element, elem_type: str):
        """Add associated code snippets to UI element."""
        if not id_val:
            return

        id_string = self._get_id_string(id_val, elem_type)
        if not id_string:
            return
            
        # For modern Android projects, also try with just the ID part (without R.id. prefix)
        id_parts = id_string.split(".")
        simple_id = id_parts[-1] if len(id_parts) > 1 else id_string
        
        # For ViewBinding, try camelCase version of the ID
        # Convert snake_case to camelCase (e.g., my_button -> myButton)
        camel_case_id = ''.join(
            word.capitalize() if i > 0 else word.lower()
            for i, word in enumerate(simple_id.split('_'))
        )
        
        # Create a list of IDs to search for
        id_variants = [id_string]
        
        # Add simple ID variant if different
        if simple_id != id_string and not simple_id.startswith("R."):
            id_variants.append(simple_id)
            
        # Add binding variant
        if camel_case_id != simple_id:
            id_variants.append(camel_case_id)
            id_variants.append(f"binding.{camel_case_id}")
            
        # Add modern binding variants (e.g., binding.myButton, viewBinding.myButton)
        for prefix in ["binding", "viewBinding", "mBinding", "b"]:
            if not any(v.startswith(f"{prefix}.") for v in id_variants):
                id_variants.append(f"{prefix}.{camel_case_id}")

        # Add onClick method from XML
        onclick = self._find_onclick_method(layout_elem)
        if onclick:
            method_elem = ET.SubElement(ui_elem, "method")
            method_elem.set("name", onclick[0])
            method_elem.set("body", onclick[1])

        # Process all ID variants
        for variant_id in id_variants:
            # Add case segments
            for name, body in self._find_case_segments(variant_id):
                method_elem = ET.SubElement(ui_elem, "method")
                method_elem.set("name", name)
                method_elem.set("body", body)

            # Add if segments
            for name, body in self._find_if_segments(variant_id):
                method_elem = ET.SubElement(ui_elem, "method")
                method_elem.set("name", name)
                method_elem.set("body", body)

            # Add relevant methods
            for name, body in self._find_relevant_methods(variant_id):
                method_elem = ET.SubElement(ui_elem, "method")
                method_elem.set("name", name)
                method_elem.set("body", body)

            # Add called methods (variable tracking like getCalledMethods in Java)
            for name, body in self._find_called_methods(variant_id):
                method_elem = ET.SubElement(ui_elem, "method")
                method_elem.set("name", name)
                method_elem.set("body", body)
                # Also try to add properties from setText/setTitle
                self._add_property(ui_elem, name, body)

        # For Preference elements, also search by alias
        if elem_type == "Preference":
            alias = self._get_alias(id_string)
            if alias:
                for name, body in self._find_case_segments(alias):
                    method_elem = ET.SubElement(ui_elem, "method")
                    method_elem.set("name", name)
                    method_elem.set("body", body)
                for name, body in self._find_if_segments(alias):
                    method_elem = ET.SubElement(ui_elem, "method")
                    method_elem.set("name", name)
                    method_elem.set("body", body)
                for name, body in self._find_relevant_methods(alias):
                    method_elem = ET.SubElement(ui_elem, "method")
                    method_elem.set("name", name)
                    method_elem.set("body", body)
                for name, body in self._find_called_methods(alias):
                    method_elem = ET.SubElement(ui_elem, "method")
                    method_elem.set("name", name)
                    method_elem.set("body", body)

    def _add_code_by_title(self, ui_elem: ET.Element, title: str):
        """
        Add associated code snippets to UI element by searching for string resource references.
        This is useful for menu items that don't have an android:id but have a title.

        Args:
            ui_elem: The UI element to add code to
            title: The string resource name (e.g., "file_manager_title")
        """
        if not title:
            return

        # Build the R.string.xxx reference
        string_ref = f"R.string.{title}"

        # Search in MethodCode.xml for code that references this string
        for java_file in self.java_files:
            for method in java_file:
                method_name = method.get("name", "")
                content = method.text or ""

                if string_ref in content:
                    # Found a method that uses this string resource
                    # Extract relevant code around the string reference
                    relevant_lines = []
                    for line in content.split("\n"):
                        if string_ref in line:
                            relevant_lines.append(line.strip())

                    if relevant_lines:
                        method_elem = ET.SubElement(ui_elem, "method")
                        method_elem.set("name", method_name)
                        method_elem.set("body", "\n".join(relevant_lines))

        # Also search in source files directly
        for path in self.source_file_paths:
            content = self._read_source_file(path)
            if string_ref in content:
                # Extract method context around the string reference
                for match in re.finditer(rf'fun\s+(\w+)[^{{]*\{{[^}}]*{re.escape(string_ref)}[^}}]*\}}', content, re.DOTALL):
                    method_name = match.group(1)
                    method_body = match.group(0)
                    method_elem = ET.SubElement(ui_elem, "method")
                    method_elem.set("name", method_name)
                    method_elem.set("body", method_body[:500])  # Limit to 500 chars

                # Also look for when/case expressions with the string
                for match in re.finditer(rf'{re.escape(string_ref)}\s*->\s*\{{([^}}]+)\}}', content):
                    method_elem = ET.SubElement(ui_elem, "method")
                    method_elem.set("name", "whenBlock")
                    method_elem.set("body", match.group(1).strip())

    def build_ui_elements(self) -> ET.Element:
        """Build ElementCode XML structure."""
        root = ET.Element("ElementCode")
        
        print(f"  Activity list: {self.activity_list}")
        print(f"  Activity to layouts mapping:")
        for activity, layouts in self.activity_to_layouts.items():
            print(f"    {activity}: {layouts}")

        for activity in self.activity_list:
            layouts = self.activity_to_layouts.get(activity, set())
            menus = self.activity_to_menus.get(activity, set())
            xmls = self.activity_to_xmls.get(activity, set())

            if not layouts and not menus and not xmls:
                continue

            activity_elem = ET.SubElement(root, "Activity")
            activity_elem.set("name", activity)

            # Process layouts
            for layout_name in layouts:
                if layout_name in self.layout_names:
                    idx = self.layout_names.index(layout_name)
                    try:
                        tree = ET.parse(self.layout_paths[idx])
                        self._add_ui_element(activity_elem, tree.getroot())
                    except ET.ParseError as e:
                        print(f"  Error parsing layout {layout_name}: {e}")

            # Process menus
            for menu_name in menus:
                if menu_name in self.menu_names:
                    idx = self.menu_names.index(menu_name)
                    try:
                        tree = ET.parse(self.menu_paths[idx])
                        self._add_ui_element(activity_elem, tree.getroot())
                    except ET.ParseError as e:
                        print(f"  Error parsing menu {menu_name}: {e}")

            # Process xmls (preferences)
            for xml_name in xmls:
                if xml_name in self.xml_names:
                    idx = self.xml_names.index(xml_name)
                    try:
                        tree = ET.parse(self.xml_paths[idx])
                        self._add_ui_element(activity_elem, tree.getroot())
                    except ET.ParseError as e:
                        print(f"  Error parsing xml {xml_name}: {e}")

        return root


def format_xml(root: ET.Element) -> ET.Element:
    """
    Format XML like DocumentFormatter.java:
    1. Remove empty elements (id="" AND text="")
    2. Split elements with [text1][text2] into multiple elements
    3. Set Preference key to "android:id/title"
    """
    for activity in list(root):
        new_elements = []
        elements_to_remove = []

        for ui_elem in list(activity):
            tag = ui_elem.tag

            if tag == "UIElement":
                id_val = ui_elem.get("id", "")
                text = ui_elem.get("text", "")
                text_content = ui_elem.get("textContent", "")

                # Remove empty elements
                if id_val == "" and text == "":
                    elements_to_remove.append(ui_elem)
                    continue

                # Split elements with [text1][text2] format
                if "[" in text:
                    text_list = text.split("[")
                    text_content_list = text_content.split("[") if text_content else [""] * len(text_list)

                    for i, text_segment in enumerate(text_list):
                        if not text_segment:
                            continue

                        # Remove trailing ]
                        text_segment = text_segment.rstrip("]")
                        text_content_segment = ""
                        if i < len(text_content_list):
                            text_content_segment = text_content_list[i].rstrip("]")

                        new_elem = ET.Element("UIElement")
                        new_elem.set("id", id_val)
                        new_elem.set("text", text_segment)
                        new_elem.set("textContent", text_content_segment)

                        # Copy method children
                        for method in ui_elem:
                            new_method = ET.SubElement(new_elem, "method")
                            new_method.set("name", method.get("name", ""))
                            new_method.set("body", method.get("body", ""))

                        new_elements.append(new_elem)

                    elements_to_remove.append(ui_elem)

            elif tag == "Preference":
                key = ui_elem.get("key", "")
                title = ui_elem.get("title", "")
                title_content = ui_elem.get("titleContent", "")

                # Remove empty elements
                if key == "" and title == "":
                    elements_to_remove.append(ui_elem)
                    continue

                # Set key to android:id/title
                ui_elem.set("key", "android:id/title")

                # Split elements with [title1][title2] format
                if "[" in title:
                    title_list = title.split("[")
                    title_content_list = title_content.split("[") if title_content else [""] * len(title_list)

                    for i, title_segment in enumerate(title_list):
                        if not title_segment:
                            continue

                        title_segment = title_segment.rstrip("]")
                        title_content_segment = ""
                        if i < len(title_content_list):
                            title_content_segment = title_content_list[i].rstrip("]")

                        new_elem = ET.Element("Preference")
                        new_elem.set("key", "android:id/title")
                        new_elem.set("title", title_segment)
                        new_elem.set("titleContent", title_content_segment)

                        # Copy method children
                        for method in ui_elem:
                            new_method = ET.SubElement(new_elem, "method")
                            new_method.set("name", method.get("name", ""))
                            new_method.set("body", method.get("body", ""))

                        new_elements.append(new_elem)

                    elements_to_remove.append(ui_elem)

        # Remove marked elements
        for elem in elements_to_remove:
            activity.remove(elem)

        # Add new split elements
        for elem in new_elements:
            activity.append(elem)

    return root


def escape_xml_attr(value: str) -> str:
    """Escape XML special characters in attribute values."""
    return (value
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
            .replace("'", "&apos;"))


def write_xml(root: ET.Element, output_path: str):
    """Write XML with proper formatting."""

    def write_element(f, elem: ET.Element, level: int):
        indent = "  " * level
        attrs = " ".join(f'{k}="{escape_xml_attr(v)}"' for k, v in elem.attrib.items())

        if attrs:
            f.write(f"{indent}<{elem.tag} {attrs}")
        else:
            f.write(f"{indent}<{elem.tag}")

        if len(elem) == 0 and not elem.text:
            f.write("/>\n")
            return

        f.write(">")

        if elem.text and elem.text.strip():
            if elem.tag == "method":
                f.write(f"<![CDATA[{elem.text}]]>")
            else:
                f.write(elem.text)

        if len(elem) > 0:
            f.write("\n")
            for child in elem:
                write_element(f, child, level + 1)
            f.write(indent)

        f.write(f"</{elem.tag}>\n")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
        write_element(f, root, 0)


def find_resource_path(source_path: str) -> Optional[str]:
    """
    Automatically find the resource path (directory containing AndroidManifest.xml and res/).
    Searches common Android project structures.
    """
    # Common patterns for Android resource locations
    patterns = [
        # Standard Android project structure
        "app/src/main",
        "*/src/main",
        "src/main",
        # Direct structure
        "",
    ]

    for pattern in patterns:
        if pattern:
            search_dirs = list(Path(source_path).glob(pattern))
        else:
            search_dirs = [Path(source_path)]

        for search_dir in search_dirs:
            manifest_path = search_dir / "AndroidManifest.xml"
            res_path = search_dir / "res"
            if manifest_path.exists() and res_path.exists():
                return str(search_dir)

    # Fallback: search for AndroidManifest.xml recursively
    for manifest in Path(source_path).rglob("AndroidManifest.xml"):
        parent = manifest.parent
        res_path = parent / "res"
        if res_path.exists():
            return str(parent)

    return None


def main():
    if len(sys.argv) < 3:
        print("Usage: python layout_analyzer.py <source_code_path> <method_code_xml> [output_dir]")
        print("Example: python layout_analyzer.py ./Anki-Android-2.23.1 ./output/Anki-Android-2.23.1_MethodCode.xml ./output")
        print("\nThe script will automatically search for AndroidManifest.xml and res/ folder.")
        sys.exit(1)

    source_path = sys.argv[1].rstrip("/")
    method_code_path = sys.argv[2]
    output_dir = sys.argv[3] if len(sys.argv) > 3 else None

    if not os.path.exists(source_path):
        print(f"Error: Source path '{source_path}' does not exist")
        sys.exit(1)

    if not os.path.exists(method_code_path):
        print(f"Error: MethodCode.xml '{method_code_path}' does not exist")
        sys.exit(1)

    # Automatically find resource path
    resource_path = find_resource_path(source_path)
    if not resource_path:
        print(f"Error: Could not find AndroidManifest.xml and res/ in '{source_path}'")
        print("Please ensure the source path contains a valid Android project structure.")
        sys.exit(1)

    # Extract app name from method code path
    app_name = os.path.basename(method_code_path).replace("_MethodCode.xml", "")

    if output_dir is None:
        output_dir = os.path.dirname(os.path.abspath(method_code_path))
        if not output_dir:
            output_dir = "."

    print(f"Source code path: {source_path}")
    print(f"Found resource path: {resource_path}")
    print(f"Using method code from: {method_code_path}")
    print(f"App name: {app_name}")
    print("-" * 50)

    # Create analyzer (pass source_path for direct source file searching)
    analyzer = AndroidLayoutAnalyzer(resource_path, method_code_path, source_path)

    print(f"Found {len(analyzer.activity_list)} activities")
    print(f"Found {len(analyzer.layout_names)} layouts, {len(analyzer.menu_names)} menus, {len(analyzer.xml_names)} xml files")
    print(f"Found {len(analyzer.source_file_paths)} source files for code searching")

    # Build activity to layout mappings
    analyzer.build_layout_list_by_activity()

    # Build UI elements
    root = analyzer.build_ui_elements()

    # Format XML (like DocumentFormatter.java)
    root = format_xml(root)

    # Count elements
    ui_count = len(root.findall(".//UIElement"))
    pref_count = len(root.findall(".//Preference"))
    method_count = len(root.findall(".//method"))

    print(f"Extracted {ui_count} UI elements, {pref_count} preferences")
    print(f"Found {method_count} associated code snippets")

    # Write output
    output_path = os.path.join(output_dir, f"{app_name}_ElementCode.xml")
    write_xml(root, output_path)

    print(f"\nOutput saved to: {output_path}")


if __name__ == "__main__":
    main()
